version: 1

disable_existing_loggers: False

formatters:
  console_formatter:
    format: '[%(asctime)s][%(levelname)s][%(name)s][%(funcName)s:%(lineno)s] %(message)s'

handlers:
  console_handler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: console_formatter
    stream: ext://sys.stdout

root:
  level: ERROR
  handlers: [console_handler]
